swagger: '2.0'
info:
  description: This is an API to get real estate offers.
  version: 1.0.0
  title: Invest AF API
  termsOfService: 'http://invest-af.com'
  contact:
    email: contact@invest-af.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Offers
    description: Get informations about the best offers.
  - name: Sessions
    description: Managing admin user sessions.
paths:
  /offers:
    get:
      tags:
        - Offers
      summary: Outputs the offers sorted from best to worst by default
      description: ''
      operationId: api.get_offers
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: city
          description: the location of the offers
          required: false
          type: string
        - in: query
          name: country
          description: the location of the offers
          required: false
          type: array
          items:
            type: string
      responses:
        '200':
          description: successful operation
        '405':
          description: Invalid input
  /sessions:
    post:
      tags:
        - Sessions
      summary: Checks if authentification is valid and returns boolean telling
        wether the user is connected or not.
      description: ''
      operationId: api.connect_admin
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: username
          description: the admin's username
          required: true
          type: string
        - in: query
          name: password
          description: the admin's password
          required: true
          type: string
      responses:
        '200':
          description: successful operation